name: build TS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.0]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}[

    - name: Install modules
      run: yarn
      
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-username: admin
        mongodb-password: admin
        mongodb-db: test
      
    - name: Run Unit Tests
      run: yarn test:unit
      
    - name: Run Integration Tests
      run: yarn test:integration
      
    - name: Build
      run: |
        yarn build
